import {z} from 'zod';
import {useApp} from './store';
import {filterProducts} from './catalog';
import {lensLabel,totals} from './rules';
// Optional browser agent tools (WebMCP). Feature-detected; the store works the same without them.
export function registerWebTools(){const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!context)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
 const bag=()=>{const cart=useApp.getState().cart??[];return{items:cart.map(l=>({productId:l.productId,name:l.product.name,quantity:l.quantity,unitPrice:l.unitPrice,lenses:lensLabel(l.product.category,l.lens,l.coating)})),totals:totals(cart.reduce((n,l)=>n+l.unitPrice*l.quantity,0),useApp.getState().promo,'standard',cart.length>0),currency:'USD cents'}};
 register({name:'search_eyewear',title:'Search eyewear',description:'Read available FORMA frames by name, shape, material, or color.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input:unknown){const{query=''}=z.object({query:z.string().max(100).optional()}).strict().parse(input??{});return filterProducts(useApp.getState().products,new URLSearchParams({q:query})).map(p=>({id:p.id,name:p.name,priceCents:p.price,shape:p.shape,material:p.material,colors:p.colors,widths:p.sizes,available:p.stock}))}});
 register({name:'read_shopping_bag',title:'Read shopping bag',description:'Read the current shopping bag and estimated totals.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:bag});
 register({name:'add_frame_to_bag',title:'Add a frame to bag',description:'Add a chosen frame with included non-prescription lenses to the shopping bag. Does not place an order.',inputSchema:{type:'object',properties:{productId:{type:'string'},quantity:{type:'integer',minimum:1,maximum:20}},required:['productId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){const v=z.object({productId:z.string(),quantity:z.number().int().min(1).max(20).default(1)}).strict().parse(input);const p=useApp.getState().products.find(p=>p.id===v.productId);if(!p)throw new Error('Choose a valid productId.');await useApp.getState().perform('/cart','POST',{productId:p.id,size:p.sizes[0],color:p.colors[0],lens:'non-prescription',coating:'standard',quantity:v.quantity});return bag()}});
 register({name:'start_checkout',title:'Start checkout',description:'Open demo checkout for the current bag. Does not submit an order or charge a payment.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){if(!useApp.getState().cart?.length)throw new Error('Your bag is empty.');history.pushState({},'','/checkout?step=1');dispatchEvent(new PopStateEvent('popstate'));return{checkoutStarted:true}}});
 return()=>lifecycle.abort();}
