// Prices in cents. sizes = frame widths; colors/swatches share an order.
const c=(name:string,hex:string,filter='none')=>({name,hex,filter});
const frames=[
 {id:'p01',name:'The Ellis',category:'optical',shape:'Rectangle',material:'Acetate',price:14500,originalPrice:0,colors:[c('Ink black','#202021'),c('Soft graphite','#57575b','grayscale(1) brightness(1.3)')],sizes:['Standard','Wide'],dimensions:'52 · 18 · 145',weight:'22 g',stock:14,tag:'Bestseller',rank:1,description:'Quiet confidence, in frame form. A clean rectangular silhouette with polished acetate and a subtle bevel. The pair you reach for without thinking.'},
 {id:'p02',name:'The Remy',category:'optical',shape:'Round',material:'Acetate',price:13500,originalPrice:16000,colors:[c('Champagne','#d7c6a5'),c('Frost','#e1e0da','grayscale(1)')],sizes:['Standard','Narrow'],dimensions:'49 · 20 · 140',weight:'19 g',stock:11,tag:'Considered classic',rank:3,description:'Light, luminous, and a little unexpected. Rounded lenses meet translucent acetate for a softer take on an everyday classic.'},
 {id:'p03',name:'The Margot',category:'optical',shape:'Cat-eye',material:'Acetate',price:16500,originalPrice:0,colors:[c('Warm tortoise','#80532c'),c('Smoky tortoise','#555451','grayscale(1)')],sizes:['Standard','Wide'],dimensions:'51 · 19 · 145',weight:'24 g',stock:8,tag:'New',rank:2,description:'A lifted corner. A little character. Our modern cat-eye brings rich, marbled acetate to a silhouette that feels both familiar and completely your own.'},
 {id:'p04',name:'The Jules',category:'optical',shape:'Round',material:'Metal',price:15500,originalPrice:0,colors:[c('Brushed gold','#b8a063'),c('Silver','#c0c0c0','grayscale(1)')],sizes:['Standard','Narrow'],dimensions:'50 · 20 · 145',weight:'15 g',stock:15,tag:'Light as air',rank:5,description:'Fine lines, thoughtful proportions. A featherweight metal frame with adjustable nose pads and warm, brushed finishes.'},
 {id:'p05',name:'The Arden',category:'optical',shape:'Square',material:'Acetate',price:15500,originalPrice:0,colors:[c('Forest','#164d41'),c('Deep teal','#17585f','hue-rotate(35deg)')],sizes:['Standard','Wide'],dimensions:'53 · 18 · 145',weight:'23 g',stock:9,tag:'New',rank:6,description:'A little bolder. A little greener. Sculpted square acetate catches the light and brings an easy sense of individuality to every day.'},
 {id:'p06',name:'The Nico',category:'optical',shape:'Aviator',material:'Metal',price:15000,originalPrice:17500,colors:[c('Charcoal','#4d4d4b')],sizes:['Standard','Wide'],dimensions:'54 · 17 · 145',weight:'17 g',stock:7,tag:'Archive price',rank:8,description:'A refined double bridge and softly curved lenses. A vintage-inspired aviator, pared down to the essentials.'},
 {id:'p07',name:'The Felix',category:'optical',shape:'Browline',material:'Mixed',price:17500,originalPrice:0,colors:[c('Chestnut','#834921'),c('Ash','#747370','grayscale(1)')],sizes:['Standard','Wide'],dimensions:'51 · 20 · 145',weight:'21 g',stock:6,tag:'Signature',rank:4,description:'Warm acetate up top, fine metal below. This browline frame strikes the balance between expressive and understated.'},
 {id:'p08',name:'The Cleo',category:'optical',shape:'Geometric',material:'Acetate',price:14000,originalPrice:0,colors:[c('Crystal','#dddeda')],sizes:['Standard','Narrow'],dimensions:'50 · 19 · 140',weight:'20 g',stock:10,tag:'New',rank:7,description:'Clear acetate. Crisp angles. A quietly expressive geometric frame that lets your face do the talking.'},
 {id:'p09',name:'The Atlas',category:'sun',shape:'Square',material:'Acetate',price:16000,originalPrice:0,colors:[c('Midnight','#26262a')],sizes:['Standard','Wide'],dimensions:'54 · 19 · 145',weight:'26 g',stock:12,tag:'Bestseller',rank:2,description:'For the long way home. A substantial square silhouette, deep dark lenses, and an easy confidence that goes everywhere.'},
 {id:'p10',name:'The Sol',category:'sun',shape:'Oval',material:'Acetate',price:15500,originalPrice:18000,colors:[c('Havana','#936031'),c('Smoke','#66665f','grayscale(1)')],sizes:['Standard','Narrow'],dimensions:'50 · 21 · 145',weight:'23 g',stock:8,tag:'Summer favorite',rank:3,description:'Small in proportion, big on personality. Warm tortoise acetate meets oval brown lenses for sun-filled afternoons.'},
 {id:'p11',name:'The Rio',category:'sun',shape:'Aviator',material:'Metal',price:18500,originalPrice:0,colors:[c('Gold / amber','#c3a969'),c('Silver / smoke','#a7a7a6','grayscale(1)')],sizes:['Standard','Wide'],dimensions:'57 · 16 · 145',weight:'19 g',stock:5,tag:'Signature',rank:1,description:'The classic aviator, made a little lighter. A fine gold frame and amber lenses bring a warm outlook to bright days.'},
 {id:'p12',name:'The Lune',category:'sun',shape:'Oval',material:'Acetate',price:15000,originalPrice:0,colors:[c('Cobalt','#2a5290'),c('Violet','#635290','hue-rotate(45deg)')],sizes:['Standard','Narrow'],dimensions:'49 · 22 · 140',weight:'22 g',stock:0,tag:'Coming back soon',rank:4,description:'A clear blue point of view. Translucent cobalt acetate and softly tinted oval lenses make this our most playful pair.'}
];
// Stored in the same JSON-string shape as the Product table; createdAt is staggered so "Newest" keeps the original order.
export const catalog=frames.map((p,i)=>{const image=`/images/frame-${String(i+1).padStart(2,'0')}.webp`;return{...p,image,images:JSON.stringify([image]),sizes:JSON.stringify(p.sizes),colors:JSON.stringify(p.colors.map(x=>x.name)),swatches:JSON.stringify(p.colors.map(({hex,filter})=>({hex,filter}))),createdAt:new Date(Date.UTC(2026,0,12-i)).toISOString()}});
// Illustrative sample reviews, labelled as samples in the UI. Each reviewer is a system user that cannot sign in.
export const sampleReviewers=[{id:'sample-alex',name:'Alex M.'},{id:'sample-sam',name:'Sam L.'},{id:'sample-taylor',name:'Taylor R.'}];
export const sampleReviews=[
 {title:'My everyday pair',text:'Beautiful finish and surprisingly light. The fit is comfortable all day, and the proportions are exactly what I was looking for.',rating:5},
 {title:'Even better in person',text:'Love the details on this frame. It arrived neatly packed with a case and cloth. Very happy with my choice.',rating:5},
 {title:'A thoughtful design',text:'Feels well made and looks lovely. I needed a small adjustment at the nose, but now the fit is just right.',rating:4}
];
