import { Hono } from 'hono';
import { getCookie, setCookie, deleteCookie } from 'hono/cookie';
import { HTTPException } from 'hono/http-exception';
import { z } from 'zod';
import { database, seedCatalog, parse, product, cartLine, order, publicUser, type Env } from './db';
import { id, hash, verify, digest } from './crypto';
import { coatingsFor, lensPrice, READING_POWERS, PAYMENTS, RETURN_REASONS, SUPPORT_TOPICS, RETURN_WINDOW_MS, totals } from '../src/lib/rules';
const app=new Hono<{Bindings:Env;Variables:{db:ReturnType<typeof database>;user:any;sessionId:string}}>();
function fail(message:string,status:400|401|403|404|409|429=400):never{throw new HTTPException(status,{message})}
const text=(max=120)=>z.string().trim().min(1).max(max);
const iso=()=>new Date().toISOString();
const email=z.string().trim().email('Enter a valid email address.').max(120).transform(v=>v.toLowerCase());
const password=z.string().min(8,'Use at least 8 characters for your password.').max(128);
const COOKIE='forma_session';
async function session(c:any,userId:string){const token=id()+id();const sid=await digest(token);await c.get('db').session.create({data:{id:sid,userId,expiresAt:new Date(Date.now()+30*864e5)}});setCookie(c,COOKIE,token,{httpOnly:true,secure:new URL(c.req.url).protocol==='https:',sameSite:'Lax',path:'/',maxAge:30*86400});return sid}
async function limit(c:any,key:string,max=12){const db=c.get('db');const challengeId='limit:'+await digest(key);const old=await db.authChallenge.findUnique({where:{id:challengeId}});if(old&&new Date(old.expiresAt)>new Date()){if(old.attempts>=max)fail('Too many attempts. Try again in 10 minutes.',429);await db.authChallenge.update({where:{id:challengeId},data:{attempts:{increment:1}}})}else await db.authChallenge.upsert({where:{id:challengeId},create:{id:challengeId,userId:'rate-limit',type:'rate-limit',value:'',attempts:1,expiresAt:new Date(Date.now()+600000)},update:{attempts:1,expiresAt:new Date(Date.now()+600000)}})}
function member(c:any,message='Sign in to continue.'){const u=c.get('user');if(u.guest)fail(message,401);return u}
async function bootstrap(c:any){const db=c.get('db'),uid=c.get('user').id;const [u,cart,wishlist,addresses,orders,requests]=await Promise.all([db.user.findUniqueOrThrow({where:{id:uid}}),db.cartItem.findMany({where:{userId:uid},include:{product:{include:{_count:{select:{reviews:true}}}}},orderBy:[{createdAt:'asc'},{id:'asc'}]}),db.wishlist.findMany({where:{userId:uid}}),db.address.findMany({where:{userId:uid},orderBy:{isDefault:'desc'}}),db.order.findMany({where:{userId:uid},orderBy:{createdAt:'desc'},take:100}),db.supportRequest.findMany({where:{userId:uid},orderBy:{createdAt:'desc'},take:3,select:{id:true,topic:true,message:true,createdAt:true}})]);return{user:publicUser(u),cart:cart.map(cartLine),wishlist:wishlist.map((x:any)=>x.productId),addresses,orders:orders.map(order),requests}}
async function createGuest(c:any){const uid=id();const u=await c.get('db').user.create({data:{id:uid,email:uid+'@guest.forma.local',name:'Guest'}});await session(c,uid);c.set('user',u);return u}
// A guest who signs in keeps their bag and saved frames; guest orders follow when the delivery email matches the account.
async function mergeGuest(c:any,guestId:string,account:any){const DB=c.env.DB;await DB.batch([
 DB.prepare('INSERT INTO "CartItem" ("id","userId","productId","size","color","lens","coating","prescription","quantity","createdAt") SELECT lower(hex(randomblob(16))),?,"productId","size","color","lens","coating","prescription","quantity","createdAt" FROM "CartItem" WHERE "userId"=? ON CONFLICT ("userId","productId","size","color","lens","coating","prescription") DO UPDATE SET "quantity"=MIN(20,"quantity"+excluded."quantity")').bind(account.id,guestId),
 DB.prepare('INSERT OR IGNORE INTO "Wishlist" ("userId","productId") SELECT ?,"productId" FROM "Wishlist" WHERE "userId"=?').bind(account.id,guestId),
 // Negative cart versions never collide with a live checkout guard.
 DB.prepare('UPDATE "Order" SET "userId"=?,"cartVersion"=-(abs(random())%1000000000000)-1 WHERE "userId"=? AND lower(json_extract("address",\'$.email\'))=?').bind(account.id,guestId,account.email),
 DB.prepare('DELETE FROM "CartItem" WHERE "userId"=?').bind(guestId),DB.prepare('DELETE FROM "Wishlist" WHERE "userId"=?').bind(guestId),
 DB.prepare('UPDATE "User" SET "cartVersion"="cartVersion"+1 WHERE "id" IN (?,?)').bind(account.id,guestId)])}
app.use('/api/*',async(c,next)=>{c.header('Cache-Control','no-store');const origin=c.req.header('Origin');if(!['GET','HEAD','OPTIONS'].includes(c.req.method)&&origin&&origin!==new URL(c.req.url).origin)fail('This request was blocked.',403);c.set('db',database(c.env));const cookie=getCookie(c,COOKIE);if(cookie){const sid=await digest(cookie);c.set('sessionId',sid);const s=await c.get('db').session.findUnique({where:{id:sid},include:{user:true}});if(s&&s.expiresAt>new Date())c.set('user',s.user)}await next()});
app.get('/api/health',c=>c.json({ok:true,mode:'demo',storage:'Prisma + D1'}));
app.get('/api/bootstrap',async c=>{await seedCatalog(c.env);if(!c.get('user'))await createGuest(c);return c.json(await bootstrap(c))});
app.get('/api/products',async c=>{await seedCatalog(c.env);const list=await c.get('db').product.findMany({orderBy:{rank:'asc'},include:{_count:{select:{reviews:true}}}});return c.json(list.map(product))});
app.post('/api/auth/register',async c=>{const b=z.object({firstName:text(50),lastName:text(50),email,password}).parse(await c.req.json());await limit(c,'register:'+b.email);const db=c.get('db');if(await db.user.findUnique({where:{email:b.email}}))fail('That email already has an account. Sign in instead.',409);const guest=c.get('user');const data={email:b.email,passwordHash:await hash(b.password),firstName:b.firstName,lastName:b.lastName,name:b.firstName+' '+b.lastName,guest:false};const u=guest?.guest?await db.user.update({where:{id:guest.id},data}):await db.user.create({data:{...data,id:id()}});if(c.get('sessionId'))await db.session.deleteMany({where:{id:c.get('sessionId')}});await session(c,u.id);c.set('user',u);return c.json(await bootstrap(c))});
app.post('/api/auth/login',async c=>{const b=z.object({email,password:z.string().min(1).max(128)}).parse(await c.req.json());await limit(c,'login:'+b.email);const db=c.get('db');const u=await db.user.findUnique({where:{email:b.email}});if(!u||!await verify(b.password,u.passwordHash))fail('The email or password doesn’t match an account.',401);const current=c.get('user');if(current?.guest&&current.id!==u.id)await mergeGuest(c,current.id,u);if(c.get('sessionId'))await db.session.deleteMany({where:{id:c.get('sessionId')}});await session(c,u.id);c.set('user',u);return c.json(await bootstrap(c))});
// Demo recovery: the code is displayed instead of emailed. Replace with a delivery provider before real accounts exist.
app.post('/api/auth/forgot',async c=>{const b=z.object({email}).parse(await c.req.json());await limit(c,'forgot:'+b.email,5);const u=await c.get('db').user.findUnique({where:{email:b.email}});const code=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0');const challengeId=id();await c.get('db').authChallenge.create({data:{id:challengeId,userId:u&&!u.guest?u.id:'unknown',type:'reset',value:await hash(code),expiresAt:new Date(Date.now()+10*60000)}});return c.json({challengeId,demoCode:code})});
app.post('/api/auth/reset',async c=>{const b=z.object({challengeId:text(),code:z.string().regex(/^\d{6}$/,'Enter the 6-digit code.'),password}).parse(await c.req.json());const db=c.get('db');const ch=await db.authChallenge.findUnique({where:{id:b.challengeId}});if(!ch||ch.type!=='reset'||ch.expiresAt<new Date()||ch.attempts>=5)fail('This code has expired. Request a new one.');await db.authChallenge.update({where:{id:ch.id},data:{attempts:{increment:1}}});if(!await verify(b.code,ch.value))fail('The verification code is incorrect.');const u=await db.user.findUnique({where:{id:ch.userId}});if(!u)fail('No account matches this email. Create an account to continue.');await db.user.update({where:{id:u.id},data:{passwordHash:await hash(b.password)}});await db.authChallenge.delete({where:{id:ch.id}});await db.session.deleteMany({where:{userId:u.id}});return c.json({ok:true})});
app.use('/api/*',async(c,next)=>{if(!c.get('user'))fail('Your session has expired. Reload the page to continue.',401);await next()});
app.post('/api/auth/logout',async c=>{if(c.get('sessionId'))await c.get('db').session.deleteMany({where:{id:c.get('sessionId')}});deleteCookie(c,COOKIE,{path:'/'});return c.json({ok:true})});
app.patch('/api/user',async c=>{const b=z.object({firstName:text(50),lastName:text(50),email,currentPassword:z.string().max(128).optional()}).parse(await c.req.json());const u=member(c),db=c.get('db');if(b.email!==u.email){await limit(c,'email-change:'+u.id);if(!b.currentPassword||!await verify(b.currentPassword,u.passwordHash))fail('Enter your current password to change your email.',403);const other=await db.user.findUnique({where:{email:b.email}});if(other&&other.id!==u.id)fail('Another account uses that email.',409)}await db.user.update({where:{id:u.id},data:{firstName:b.firstName,lastName:b.lastName,name:b.firstName+' '+b.lastName,email:b.email}});return c.json(await bootstrap(c))});
app.post('/api/security/password',async c=>{const b=z.object({currentPassword:z.string().max(128),password}).parse(await c.req.json());const u=member(c);await limit(c,'password:'+u.id);if(!await verify(b.currentPassword,u.passwordHash))fail('Your current password doesn’t match.',403);await c.get('db').user.update({where:{id:u.id},data:{passwordHash:await hash(b.password)}});await c.get('db').session.deleteMany({where:{userId:u.id,id:{not:c.get('sessionId')}}});return c.json({ok:true})});
app.post('/api/wishlist/:id',async c=>{const uid=c.get('user').id,pid=c.req.param('id');if(!await c.get('db').product.findUnique({where:{id:pid}}))fail('Frame not found.',404);const where={userId_productId:{userId:uid,productId:pid}},existing=await c.get('db').wishlist.findUnique({where});if(existing)await c.get('db').wishlist.delete({where});else await c.get('db').wishlist.create({data:{userId:uid,productId:pid}});return c.json(await bootstrap(c))});
const eye=z.object({eye:z.enum(['right','left']),sphere:z.number().min(-12).max(12).multipleOf(.25),cylinder:z.number().min(-6).max(6).multipleOf(.25).default(0),axis:z.number().int().min(0).max(180).default(0)}).refine(e=>e.cylinder===0||e.axis>=1,'Enter an axis for each non-zero cylinder.');
const singleVision=z.object({pd:z.number().min(50).max(80).multipleOf(.5),eyes:z.tuple([eye,eye])}).refine(r=>r.eyes[0].eye!==r.eyes[1].eye,'Enter the sphere for both eyes.');
const reading=z.object({power:z.enum(READING_POWERS as [string,...string[]])});
const selection=z.object({size:text(30),color:text(40),lens:z.enum(['non-prescription','single-vision','reading']),coating:text(30),prescription:z.unknown().optional()});
// Validates a frame + lens choice against the product and returns its canonical stored form.
function configure(p:any,b:z.infer<typeof selection>){
 if(!parse(p.sizes).includes(b.size)||!parse(p.colors).includes(b.color)||!coatingsFor(p.category).some(x=>x.id===b.coating))fail('Choose your frame and lenses again.');
 let prescription='';
 if(b.lens!=='non-prescription'){const r=(b.lens==='single-vision'?singleVision:reading).safeParse(b.prescription);if(!r.success)fail(b.prescription==null?'Add your prescription before adding this pair.':r.error.issues.find(i=>i.code==='custom')?.message??'Check your prescription values.');prescription=JSON.stringify(r.data)}
 return{size:b.size,color:b.color,lens:b.lens,coating:b.coating,prescription};
}
async function inBag(c:any,productId:string,exceptId=''){const lines=await c.get('db').cartItem.findMany({where:{userId:c.get('user').id,productId,id:{not:exceptId}}});return lines.reduce((s:number,l:any)=>s+l.quantity,0)}
const upsertLine=(c:any,uid:string,productId:string,x:ReturnType<typeof configure>,quantity:number)=>c.env.DB.prepare('INSERT INTO "CartItem" ("id","userId","productId","size","color","lens","coating","prescription","quantity","createdAt") VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT ("userId","productId","size","color","lens","coating","prescription") DO UPDATE SET "quantity"="quantity"+excluded."quantity"').bind(id(),uid,productId,x.size,x.color,x.lens,x.coating,x.prescription,quantity,iso());
const bumpCart=(c:any,uid:string)=>c.env.DB.prepare('UPDATE "User" SET "cartVersion"="cartVersion"+1 WHERE "id"=?').bind(uid);
async function commit(c:any,statements:any[],message='That quantity is not available.'){try{await c.env.DB.batch(statements)}catch{fail(message,409)}}
app.post('/api/cart',async c=>{const b=selection.extend({productId:text(),quantity:z.number().int().min(1).max(20)}).parse(await c.req.json());const p=await c.get('db').product.findUnique({where:{id:b.productId}});if(!p)fail('Frame not found.',404);const x=configure(p,b);if(await inBag(c,p.id)+b.quantity>p.stock)fail('There aren’t enough pairs available for that quantity.');const uid=c.get('user').id;await commit(c,[upsertLine(c,uid,p.id,x,b.quantity),bumpCart(c,uid)]);return c.json(await bootstrap(c))});
// Quantity changes and lens edits share one path; an edited line merges into an identical existing one.
app.patch('/api/cart/:id',async c=>{const b=selection.partial().extend({quantity:z.number().int().min(1).max(20).optional()}).parse(await c.req.json());const uid=c.get('user').id;const line=await c.get('db').cartItem.findFirst({where:{id:c.req.param('id'),userId:uid},include:{product:true}});if(!line)fail('That pair is no longer in your bag.',404);const quantity=b.quantity??line.quantity;if(await inBag(c,line.productId,line.id)+quantity>line.product.stock)fail('That quantity is not available.');const x=configure(line.product,{...line,prescription:parse(line.prescription,null),...b} as any);const same=x.size===line.size&&x.color===line.color&&x.lens===line.lens&&x.coating===line.coating&&x.prescription===line.prescription;await commit(c,[...(same?[c.env.DB.prepare('UPDATE "CartItem" SET "quantity"=? WHERE "id"=? AND "userId"=?').bind(quantity,line.id,uid)]:[c.env.DB.prepare('DELETE FROM "CartItem" WHERE "id"=? AND "userId"=?').bind(line.id,uid),upsertLine(c,uid,line.productId,x,quantity)]),bumpCart(c,uid)]);return c.json(await bootstrap(c))});
app.delete('/api/cart/:id',async c=>{const uid=c.get('user').id;await c.env.DB.batch([c.env.DB.prepare('DELETE FROM "CartItem" WHERE "id"=? AND "userId"=?').bind(c.req.param('id'),uid),bumpCart(c,uid)]);return c.json(await bootstrap(c))});
const addressSchema=z.object({firstName:text(50),lastName:text(50),line1:text(180),line2:z.string().trim().max(100).default(''),city:text(70),state:z.string().trim().max(70).default(''),country:text(80),postalCode:text(20),phone:z.string().trim().regex(/^[+0-9() .-]{6,25}$/,'Enter a valid phone number.')});
async function saveAddress(c:any,a:z.infer<typeof addressSchema>,existingId='',isDefault=false){const db=c.get('db'),uid=c.get('user').id;const count=await db.address.count({where:{userId:uid}});const existing=existingId?await db.address.findFirst({where:{id:existingId,userId:uid}}):null;if(existingId&&!existing)fail('Address not found.',404);if(!existing&&count>=12)fail('You can save up to 12 addresses.');const makeDefault=isDefault||count===0;if(makeDefault)await db.address.updateMany({where:{userId:uid},data:{isDefault:false}});if(existing)await db.address.update({where:{id:existing.id},data:{...a,isDefault:makeDefault||existing.isDefault}});else await db.address.create({data:{...a,id:id(),userId:uid,isDefault:makeDefault}})}
app.post('/api/addresses',async c=>{member(c,'Sign in to save addresses.');const b=addressSchema.extend({isDefault:z.boolean().default(false)}).parse(await c.req.json());const{isDefault,...a}=b;await saveAddress(c,a,'',isDefault);return c.json(await bootstrap(c))});
app.patch('/api/addresses/:id',async c=>{member(c,'Sign in to save addresses.');const b=addressSchema.partial().extend({isDefault:z.boolean().optional()}).parse(await c.req.json());const db=c.get('db'),uid=c.get('user').id;const a=await db.address.findFirst({where:{id:c.req.param('id'),userId:uid}});if(!a)fail('Address not found.',404);const{isDefault,...rest}=b;const{id:_,userId:__,isDefault:old,...current}=a;await saveAddress(c,addressSchema.parse({...current,...rest}),a.id,isDefault===true);return c.json(await bootstrap(c))});
app.delete('/api/addresses/:id',async c=>{const uid=member(c).id,db=c.get('db');await db.address.deleteMany({where:{id:c.req.param('id'),userId:uid}});const left=await db.address.findMany({where:{userId:uid}});if(left.length&&!left.some((a:any)=>a.isDefault))await db.address.update({where:{id:left[0].id},data:{isDefault:true}});return c.json(await bootstrap(c))});
app.post('/api/checkout',async c=>{const b=z.object({address:addressSchema.extend({email}),delivery:z.enum(['standard','express']),payment:z.enum(PAYMENTS),coupon:z.string().trim().max(40).default(''),terms:z.literal(true,{message:'Please agree to the demo order terms.'}),saveAddress:z.boolean().default(false),idempotencyKey:z.string().uuid()}).parse(await c.req.json());const db=c.get('db'),uid=c.get('user').id;
 const existing=await db.order.findUnique({where:{userId_idempotencyKey:{userId:uid,idempotencyKey:b.idempotencyKey}}});if(existing)return c.json({order:order(existing),state:await bootstrap(c)});
 const lines=await db.cartItem.findMany({where:{userId:uid},include:{product:true},orderBy:[{createdAt:'asc'},{id:'asc'}]});if(!lines.length)fail('Your bag is empty.');
 const wanted=new Map<string,number>();for(const l of lines)wanted.set(l.productId,(wanted.get(l.productId)??0)+l.quantity);
 for(const l of lines)if(wanted.get(l.productId)!>l.product.stock)fail(`${l.product.name} has only ${l.product.stock} pairs available. Adjust the quantity in your bag.`);
 const coupon=b.coupon.toUpperCase();if(coupon&&coupon!=='WELCOME10'&&coupon!=='FORMA20')fail('That code isn’t valid. Try WELCOME10 or FORMA20.');
 const items=lines.map((l:any)=>({productId:l.productId,name:l.product.name,image:l.product.image,category:l.product.category,size:l.size,color:l.color,lens:l.lens,coating:l.coating,prescription:parse(l.prescription,null),quantity:l.quantity,price:l.product.price+lensPrice(l.product.category,l.lens,l.coating)}));
 const t=totals(items.reduce((s:number,l:any)=>s+l.price*l.quantity,0),coupon,b.delivery);
 const user=await db.user.findUniqueOrThrow({where:{id:uid}}),oid='FRM-'+Date.now().toString(36).toUpperCase()+'-'+id().slice(0,4).toUpperCase(),time=iso();
 const cash=b.payment.startsWith('Cash');
 const statements=[c.env.DB.prepare('INSERT INTO "OperationGuard" ("id","valid") VALUES (?,(SELECT CASE WHEN "cartVersion"=? THEN 1 ELSE 0 END FROM "User" WHERE "id"=?))').bind(oid,user.cartVersion,uid),...[...wanted].map(([pid,q])=>c.env.DB.prepare('UPDATE "Product" SET "stock"="stock"-?,"sold"="sold"+? WHERE "id"=?').bind(q,q,pid)),c.env.DB.prepare('INSERT INTO "Order" ("id","userId","cartVersion","idempotencyKey","status","items","subtotal","discount","shipping","tax","total","address","shippingMethod","paymentMethod","coupon","events","createdAt","updatedAt") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(oid,uid,user.cartVersion,b.idempotencyKey,'placed',JSON.stringify(items),t.subtotal,t.discount,t.shipping,t.tax,t.total,JSON.stringify(b.address),b.delivery,b.payment,t.promo??'',JSON.stringify([{status:'placed',time,text:cash?'Order confirmed — payment due on delivery (simulated)':'Order confirmed — demo payment recorded'}]),time,time),c.env.DB.prepare('DELETE FROM "CartItem" WHERE "userId"=?').bind(uid),bumpCart(c,uid),c.env.DB.prepare('DELETE FROM "OperationGuard" WHERE "id"=?').bind(oid)];
 try{await c.env.DB.batch(statements)}catch{const done=await db.order.findUnique({where:{userId_idempotencyKey:{userId:uid,idempotencyKey:b.idempotencyKey}}});if(done)return c.json({order:order(done),state:await bootstrap(c)});fail('Your bag or available stock changed. Review it and try again.',409)}
 if(b.saveAddress&&!user.guest){const{email:_,...a}=b.address;const same=await db.address.findFirst({where:{userId:uid,line1:a.line1,postalCode:a.postalCode}});await saveAddress(c,a,same?.id??'')}
 return c.json({order:order(await db.order.findUniqueOrThrow({where:{id:oid}})),state:await bootstrap(c)},201)});
async function ownOrder(c:any){const o=await c.get('db').order.findFirst({where:{id:c.req.param('id'),userId:c.get('user').id}});if(!o)fail('Order not found.',404);return o}
// Status changes are guarded on the status we read, so concurrent clicks can't double-restock.
async function transition(c:any,o:any,next:string,text:string,{restock=false,returnReason}:{restock?:boolean;returnReason?:string}={}){const guard=id(),time=iso(),DB=c.env.DB;await commit(c,[DB.prepare('INSERT INTO "OperationGuard" ("id","valid") VALUES (?,(SELECT CASE WHEN "status"=? THEN 1 ELSE 0 END FROM "Order" WHERE "id"=?))').bind(guard,o.status,o.id),...(restock?parse(o.items).map((l:any)=>DB.prepare('UPDATE "Product" SET "stock"="stock"+?,"sold"=MAX(0,"sold"-?) WHERE "id"=?').bind(l.quantity,l.quantity,l.productId)):[]),DB.prepare('UPDATE "Order" SET "status"=?,"updatedAt"=?,"events"=?,"returnReason"=? WHERE "id"=?').bind(next,time,JSON.stringify([...parse(o.events),{status:next,time,text}]),returnReason??o.returnReason,o.id),DB.prepare('DELETE FROM "OperationGuard" WHERE "id"=?').bind(guard)],'The order changed. Refresh and try again.');return c.json(await bootstrap(c))}
const ADVANCE:Record<string,[string,string]>={placed:['processing','Your pair is being prepared'],processing:['shipped','Your pair is with the demo courier'],shipped:['delivered','Delivered (simulated)'],return_requested:['returned','Return completed — demo refund recorded, stock restored']};
app.post('/api/orders/:id/advance',async c=>{const o=await ownOrder(c);const step=ADVANCE[o.status];if(!step)fail('This order has no remaining delivery steps.');return transition(c,o,step[0],step[1],{restock:step[0]==='returned'})});
app.post('/api/orders/:id/cancel',async c=>{const o=await ownOrder(c);if(!['placed','processing'].includes(o.status))fail('This order has already shipped. Request a return once it’s delivered.');return transition(c,o,'cancelled','Order cancelled — demo payment refunded, stock restored',{restock:true})});
app.post('/api/orders/:id/return',async c=>{const b=z.object({reason:z.enum(RETURN_REASONS)}).parse(await c.req.json());const o=await ownOrder(c);if(o.status!=='delivered')fail('This order is not available for a return.');const delivered=parse(o.events).reverse().find((e:any)=>e.status==='delivered')?.time??o.updatedAt;if(Date.now()-new Date(delivered).getTime()>RETURN_WINDOW_MS)fail('The 30-day return window has ended.');return transition(c,o,'return_requested','Return requested: '+b.reason,{returnReason:b.reason})});
app.post('/api/orders/:id/reorder',async c=>{const o=await ownOrder(c),uid=c.get('user').id,db=c.get('db');const items=parse(o.items),st:any[]=[],adding=new Map<string,number>();for(const item of items){const p=await db.product.findUnique({where:{id:item.productId}});if(!p)fail(`${item.name} is no longer available.`);const x=configure(p,item);adding.set(p.id,(adding.get(p.id)??0)+item.quantity);if(await inBag(c,p.id)+adding.get(p.id)!>p.stock)fail(`${p.name} doesn’t have enough pairs available.`);st.push(upsertLine(c,uid,p.id,x,item.quantity))}await commit(c,[...st,bumpCart(c,uid)],'Your bag already has the maximum quantity for one of these frames.');return c.json(await bootstrap(c))});
app.get('/api/products/:id/reviews',async c=>{const uid=c.get('user').id;const reviews=await c.get('db').review.findMany({where:{productId:c.req.param('id')},include:{comments:{orderBy:{createdAt:'asc'},select:{id:true,author:true,text:true,createdAt:true}}},orderBy:[{sample:'asc'},{createdAt:'desc'}]});return c.json(reviews.map((r:any)=>({...r,liked:parse(r.likedBy).includes(uid),mine:r.userId===uid,likedBy:undefined,userId:undefined})))});
app.post('/api/products/:id/reviews',async c=>{const b=z.object({rating:z.number().int().min(1).max(5),title:z.string().trim().min(3,'Please add a headline.').max(90),text:z.string().trim().min(10,'Please add a little more detail.').max(2000)}).parse(await c.req.json());const u=member(c,'Sign in to share your perspective.'),db=c.get('db'),pid=c.req.param('id');if(!await db.product.findUnique({where:{id:pid}}))fail('Frame not found.',404);if(await db.review.findUnique({where:{userId_productId:{userId:u.id,productId:pid}}}))fail('You already reviewed this frame.',409);const orders=await db.order.findMany({where:{userId:u.id,status:{notIn:['cancelled','returned']}}});const verified=orders.some((o:any)=>parse(o.items).some((l:any)=>l.productId===pid));await db.review.create({data:{id:id(),userId:u.id,productId:pid,...b,author:u.firstName+' '+u.lastName.slice(0,1)+'.',verified}});const avg=await db.review.aggregate({where:{productId:pid},_avg:{rating:true}});await db.product.update({where:{id:pid},data:{rating:avg._avg.rating??4.7}});return c.json({ok:true})});
app.post('/api/reviews/:id/like',async c=>{const r=await c.get('db').review.findUnique({where:{id:c.req.param('id')}});if(!r)fail('Review not found.',404);const uid=c.get('user').id,old=parse(r.likedBy) as string[],next=old.includes(uid)?old.filter(v=>v!==uid):[...old,uid];await c.get('db').review.update({where:{id:r.id},data:{likes:next.length,likedBy:JSON.stringify(next)}});return c.json({liked:next.includes(uid),likes:next.length})});
app.post('/api/reviews/:id/comments',async c=>{const b=z.object({text:z.string().trim().min(3,'Add a little more detail.').max(1000)}).parse(await c.req.json());const u=member(c,'Sign in to join the conversation.');if(!await c.get('db').review.findUnique({where:{id:c.req.param('id')}}))fail('Review not found.',404);await c.get('db').reviewComment.create({data:{id:id(),reviewId:c.req.param('id'),userId:u.id,author:u.firstName,text:b.text}});return c.json({ok:true})});
app.post('/api/support',async c=>{const b=z.object({name:text(80),email,topic:z.enum(SUPPORT_TOPICS),message:z.string().trim().min(10,'Please add a little more detail.').max(3000)}).parse(await c.req.json());await limit(c,'support:'+c.get('user').id,10);await c.get('db').supportRequest.create({data:{...b,id:'HELP-'+Date.now().toString(36).toUpperCase(),userId:c.get('user').id}});return c.json(await bootstrap(c))});
app.post('/api/newsletter',async c=>{const b=z.object({email}).parse(await c.req.json());const r=await c.env.DB.prepare('INSERT OR IGNORE INTO "NewsletterSubscriber" ("email","createdAt") VALUES (?,?)').bind(b.email,iso()).run();return c.json({subscribed:r.meta.changes===1})});
app.post('/api/restock',async c=>{const b=z.object({productId:text(),email}).parse(await c.req.json());if(!await c.get('db').product.findUnique({where:{id:b.productId}}))fail('Frame not found.',404);await c.env.DB.prepare('INSERT OR IGNORE INTO "RestockRequest" ("productId","email","createdAt") VALUES (?,?,?)').bind(b.productId,b.email,iso()).run();return c.json({ok:true})});
app.onError((err,c)=>{if(err instanceof HTTPException)return c.json({error:err.message},err.status);if(err instanceof z.ZodError)return c.json({error:err.issues[0]?.message??'Check the information and try again.',fields:err.issues.map(i=>({path:i.path.join('.'),message:i.message}))},400);console.error('FORMA API error',err);return c.json({error:'Something went wrong. Your changes were not saved. Please try again.'},500)});
app.all('/api/*',c=>c.json({error:'This endpoint does not exist.'},404));
export default {async fetch(request:Request,env:Env,ctx:ExecutionContext){if(new URL(request.url).pathname.startsWith('/api/'))return app.fetch(request,env,ctx);if(env.ASSETS){let response=await env.ASSETS.fetch(request);if(response.status===404&&request.method==='GET'&&!new URL(request.url).pathname.split('/').at(-1)?.includes('.'))response=await env.ASSETS.fetch(new Request(new URL('/index.html',request.url),request));return response;}return new Response('The FORMA client is served by Vite during development.',{status:404})}};
