import {Link,useSearchParams} from 'react-router-dom';
import {toast} from 'sonner';
import {Breadcrumb,FormError,PageTitle,NONE,useSubmit} from '@/components/common';
import {useApp} from '@/lib/store';
import {LENS_TYPES,SUPPORT_TOPICS} from '@/lib/rules';
import {money} from '@/lib/utils';
export function Guide(){return<div className="page-wrap"><div className="content-page"><Breadcrumb parts={[{label:'Lens & fit guide'}]}/><div className="page-heading"><span className="eyebrow">Good things to know</span><h1>Clarity, considered.</h1><p>A simple guide to finding your fit and choosing your lenses.</p></div>
 <h2>Choose your point of view.</h2><div className="guide-grid">{LENS_TYPES.map(l=><div key={l.id} className="guide-card"><h3>{l.name}</h3><p>{l.description}</p><div className="guide-price">{l.price?'Add '+money(l.price):'Included with your frame'}</div></div>)}<div className="guide-card"><h3>Finishing touches</h3><p>For optical frames, choose standard clear, blue-light filtering, or light-adaptive lenses. Sunglasses offer standard UV lenses or a polarized upgrade.</p><div className="guide-price">Lens upgrades from $20</div></div></div>
 <h2>Find your fit.</h2><p className="muted" style={{marginTop:18}}>The three numbers on your frame are lens width, bridge width, and temple length, in millimeters. Compare them with a pair that already fits well.</p>
 <table className="fit-table"><thead><tr><th>Frame width</th><th>A good starting point</th><th>How it should feel</th></tr></thead><tbody><tr><td>Narrow</td><td>Smaller faces / 49–50 mm lenses</td><td>Stable without pinching</td></tr><tr><td>Standard</td><td>Most faces / 50–54 mm lenses</td><td>Balanced at the nose and temples</td></tr><tr><td>Wide</td><td>Broader faces / 53–57 mm lenses</td><td>Room at the temples</td></tr></tbody></table>
 <p className="form-note">Fit labels are illustrative in this demo. Prescription measurements should come from an eye-care professional. This guide doesn't replace an eye exam.</p><div style={{textAlign:'center',marginTop:40}}><Link className="button" to="/catalog">Find your frame</Link></div></div></div>}
export function About(){return<div className="page-wrap"><div className="content-page"><Breadcrumb parts={[{label:'Our world'}]}/><div className="page-heading"><span className="eyebrow">Made with intention</span><h1>A different way<br/>to <span className="serif">see things.</span></h1><p>Good eyewear should be a pleasure to wear. A considered shape, the right balance, a little character. That's where FORMA begins.</p></div>
 <img src="/images/hero.webp" alt="A closer look at our eyewear campaign" style={{width:'100%',aspectRatio:1.9,objectFit:'cover',objectPosition:'center 40%'}}/>
 <div className="guide-grid" style={{marginTop:40}}><div className="guide-card"><h3>Everyday, with intention.</h3><p>Our collection brings together expressive acetate, delicate metals, and familiar shapes with a fresh perspective. Frames that fit your day, without taking it over.</p></div><div className="guide-card"><h3>A pair that feels like you.</h3><p>Choose a shape, find your width, and select your lenses. Whether you're heading to work or taking the long way home, there is a frame for that version of you.</p></div></div><div style={{textAlign:'center'}}><Link className="button" to="/catalog">Meet the collection</Link></div></div></div>}
const FAQS=[['What is included with my frame?','Every frame includes standard non-prescription lenses, a protective case, and a microfiber cloth. Prescription lenses and optional lens finishes have the prices shown in the lens selector.'],['How long does delivery take?','Standard delivery is 5–7 business days and express is 2–3 business days. Prescription lenses add 3–5 business days. This demo simulates shipping; it does not dispatch physical products.'],['Can I return my glasses?','Once an order is marked delivered, you can request a return within 30 days from its order page. In this demo, you can complete the return using the delivery simulator.'],['How do I add my prescription?','Open a frame, choose your lenses, and select single vision. Enter the values from your prescription, including PD. This demo saves those choices with your pair. An actual store would verify the prescription before fulfillment.'],['Where are my orders and details stored?','Your bag, orders, and account are saved by the FORMA demo server, so they follow your session. No payment provider, email service, or fulfillment system is connected.'],['How do I use a discount code?','Add your frames to the bag and enter WELCOME10 for 10% off, or FORMA20 for $20 off a subtotal of $200 or more. One code can be used at a time.']];
export function Help(){
 const[params]=useSearchParams(),user=useApp(s=>s.user),requests=useApp(s=>s.requests??NONE),perform=useApp(s=>s.perform),{error,busy,submit}=useSubmit();const member=user&&!user.guest;
 return<div className="page-wrap"><div className="content-page"><Breadcrumb parts={[{label:'Here to help'}]}/><div className="page-heading"><span className="eyebrow">Here to help</span><h1>A little clarity.</h1><p>Find an answer, manage an order, or leave a demo support request.</p></div><div className="help-layout">
  <div className="faq-list"><h2 style={{fontSize:'1.6rem',marginBottom:20}}>Good questions.</h2>{FAQS.map(([q,a],i)=><details key={q} open={params.get('topic')==='shipping'&&i===1}><summary>{q}</summary><p>{a}</p></details>)}</div>
  <form className="contact-form" onSubmit={submit(async(f,form)=>{await perform('/support','POST',f,{silent:true});form.reset();toast('Demo support request saved. It hasn’t been sent to a team.')})}><h2>Leave us a note.</h2><div className="form-grid"><div className="field full"><label htmlFor="contact-name">Your name</label><input id="contact-name" name="name" defaultValue={member?user.name:''} maxLength={80} autoComplete="name" required/></div><div className="field full"><label htmlFor="contact-email">Email</label><input id="contact-email" name="email" type="email" defaultValue={member?user.email:''} maxLength={120} autoComplete="email" required/></div><div className="field full"><label htmlFor="contact-topic">What is it about?</label><select id="contact-topic" name="topic">{SUPPORT_TOPICS.map(t=><option key={t}>{t}</option>)}</select></div><div className="field full"><label htmlFor="contact-message">Your message</label><textarea id="contact-message" name="message" maxLength={3000} minLength={10} required/></div></div>
   <FormError message={error}/><button className="button full" disabled={busy} style={{marginTop:20}}>Save demo request</button><p className="form-note">Requests are saved for this demo store. They aren't sent to a support team.</p>{requests.map(t=><p key={t.id} className="form-note" style={{borderTop:'1px solid var(--line)',paddingTop:12}}>{t.id} · {t.topic}<br/>{t.message}</p>)}</form>
 </div></div></div>
}
export function Legal(){const[params]=useSearchParams(),privacy=params.get('type')==='privacy';
 return<div className="page-wrap"><div className="content-page legal-copy"><Breadcrumb parts={[{label:privacy?'Privacy':'Terms'}]}/><PageTitle title={privacy?'Your privacy.':'The small print.'}/><h2>A demo store</h2><p>FORMA is a demonstration storefront. Product names, prices, stock, and policies are illustrative. No purchase creates a physical order, real charge, or outgoing email.</p>
  {privacy?<><h2>What is saved</h2><p>The demo server saves your account, bag, favorites, addresses, lens selections, orders, reviews, and requests. A session cookie keeps you signed in; your device remembers recently viewed frames, comparisons, and checkout progress. No analytics or tracking scripts are used.</p><h2>Keep real details private</h2><p>Use made-up contact details and a demo password. This store is not a production prescription-handling system. No real card details are requested.</p></>
  :<><h2>Shopping and checkout</h2><p>Standard lenses are included in frame prices. Selected lens upgrades, delivery charges, discounts, and an illustrative 8% tax are shown before checkout. All payment methods are simulated.</p><h2>Returns in the demo</h2><p>Orders can be cancelled before shipping. After simulated delivery, a return may be requested within 30 days. Completing a demo return restores stock and records a simulated refund.</p><h2>Before a live store</h2><p>A production store needs verified email delivery, secure payment processing, prescription review, and order fulfillment services.</p></>}
  <Link className="text-button" to="/catalog" style={{marginTop:30,display:'inline-block'}}>Back to the collection</Link></div></div>}
